# Activated when the profile is 'local'
spring:
  config:
    activate:
      on-profile: local

  datasource:
    url: "jdbc:h2:mem:library;MODE=MYSQL;NON_KEYWORDS=USER"
    username: sa
    password:
    driver-class-name: org.h2.Driver

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        dialect: org.hibernate.dialect.H2Dialect

  h2:
    console:
#      H2 Web console active
      enabled: true
#      Activated H2 Web console's address
      path: /h2-console

---
# Activated when the profile is 'dev'
spring:
  config:
    activate:
      on-profile: dev

  datasource:
    url: "jdbc:mysql://localhost/library"
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: "root"
    password: "Abcd1234!"

  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: true
        show_sql: true

  thymeleaf:
    prefix: classpath:/templates/